package ya.practicum.blog.db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Set;

/**
 * Introduces {@code tags} and {@code post_tags}, backfills from legacy {@code posts.tags} CSV, then drops that column.
 */
public class V4__Normalize_tags extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        try (Statement st = connection.createStatement()) {
            st.execute("""
                    CREATE TABLE tags (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(64) NOT NULL,
                        CONSTRAINT uq_tags_name UNIQUE (name)
                    )
                    """);
            st.execute("""
                    CREATE TABLE post_tags (
                        post_id BIGINT NOT NULL,
                        tag_id BIGINT NOT NULL,
                        tag_position INT NOT NULL,
                        CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
                        CONSTRAINT fk_post_tags_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
                        CONSTRAINT fk_post_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
                    )
                    """);
            st.execute("CREATE INDEX idx_post_tags_post_id ON post_tags(post_id)");
            st.execute("CREATE INDEX idx_post_tags_tag_id ON post_tags(tag_id)");
        }

        try (PreparedStatement selectPosts = connection.prepareStatement("SELECT id, tags FROM posts");
             ResultSet rs = selectPosts.executeQuery()) {
            while (rs.next()) {
                long postId = rs.getLong(1);
                String csv = rs.getString(2);
                if (csv == null || csv.isBlank()) {
                    continue;
                }
                Set<String> seen = new LinkedHashSet<>();
                int position = 0;
                for (String part : csv.split(",")) {
                    String name = part.trim().toLowerCase(Locale.ROOT);
                    if (name.isEmpty() || !seen.add(name)) {
                        continue;
                    }
                    long tagId = findOrCreateTag(connection, name);
                    try (PreparedStatement ins = connection.prepareStatement(
                            "INSERT INTO post_tags (post_id, tag_id, tag_position) VALUES (?, ?, ?)")) {
                        ins.setLong(1, postId);
                        ins.setLong(2, tagId);
                        ins.setInt(3, position++);
                        ins.executeUpdate();
                    }
                }
            }
        }

        try (Statement st = connection.createStatement()) {
            st.execute("ALTER TABLE posts DROP COLUMN tags");
        }
    }

    private static long findOrCreateTag(Connection connection, String normalizedName) throws Exception {
        try (PreparedStatement sel = connection.prepareStatement("SELECT id FROM tags WHERE name = ?")) {
            sel.setString(1, normalizedName);
            try (ResultSet rs = sel.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong(1);
                }
            }
        }
        try (PreparedStatement ins = connection.prepareStatement(
                "INSERT INTO tags (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            ins.setString(1, normalizedName);
            ins.executeUpdate();
            try (ResultSet keys = ins.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getLong(1);
                }
            }
        }
        try (PreparedStatement sel = connection.prepareStatement("SELECT id FROM tags WHERE name = ?")) {
            sel.setString(1, normalizedName);
            try (ResultSet rs = sel.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong(1);
                }
            }
        }
        throw new IllegalStateException("Failed to resolve tag id for: " + normalizedName);
    }
}
