spring.datasource.url=jdbc:postgresql://localhost:5432/my_blog
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
logging.config=classpath:logback-dev.xml
